version: "3"

services:
  flask_app:
    container_name: flask_app
    build: ./flask_app
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx_container
    build: ./nginx
    ports:
      - "4000:4000"
    depends_on:
      - flask_app
